import type { DashboardData } from "./types";

export function getMockDashboard(): DashboardData {
  return {
    meetings: [
      {
        id: "m-001",
        title: "经营预算复盘",
        owner: "陈越",
        status: "ended",
        startTime: "2026-04-30 09:30",
        duration: "58 分钟",
        participants: 18,
        summary: "确认预算审批、客户存储接入和会后处理优先级。",
        storageUri: "s3://meeting-assets/mock/m-001/summary.md",
        roomName: "meeting-m-001",
      },
      {
        id: "m-002",
        title: "产品迭代评审",
        owner: "周敏",
        status: "live",
        startTime: "2026-04-30 14:00",
        duration: "进行中",
        participants: 9,
        summary: "正在讨论 LiveKit 录制、mock API 与搜索入口。",
        storageUri: "s3://meeting-assets/mock/m-002/live",
        roomName: "meeting-m-002",
      },
      {
        id: "m-003",
        title: "客户交付同步",
        owner: "林辰",
        status: "scheduled",
        startTime: "2026-05-01 10:00",
        duration: "45 分钟",
        participants: 12,
        summary: "待启动客户 NAS 网关和身份映射配置确认。",
        storageUri: "nas:///mnt/customer-meeting-assets/mock/m-003",
        roomName: "meeting-m-003",
      },
    ],
    jobs: [
      {
        id: "job-001",
        meetingId: "m-001",
        title: "经营预算复盘",
        status: "done",
        stage: "归档完成",
        progress: 100,
        updatedAt: "2026-04-30 10:34",
      },
      {
        id: "job-002",
        meetingId: "m-002",
        title: "产品迭代评审",
        status: "processing",
        stage: "摘要生成",
        progress: 68,
        updatedAt: "2026-04-30 14:26",
      },
      {
        id: "job-003",
        meetingId: "m-003",
        title: "客户交付同步",
        status: "queued",
        stage: "等待录制事件",
        progress: 8,
        updatedAt: "2026-04-30 14:10",
      },
    ],
    middleware: [
      {
        name: "PostgreSQL",
        role: "控制面数据、全文检索",
        status: "ready",
        endpoint: "postgres:5432",
        configFile: "infra/docker/docker-compose.local.yml",
      },
      {
        name: "Redis",
        role: "Asynq broker、任务状态缓存",
        status: "ready",
        endpoint: "redis:6379",
        configFile: "infra/docker/docker-compose.local.yml",
      },
      {
        name: "MinIO",
        role: "S3 兼容会议资产存储",
        status: "mocked",
        endpoint: "minio:9000",
        configFile: "config/storage.s3.example.json",
      },
      {
        name: "LiveKit",
        role: "RTC 房间、屏幕共享、录制事件",
        status: "mocked",
        endpoint: "livekit:7880",
        configFile: "infra/docker/livekit.yaml",
      },
      {
        name: "ASR",
        role: "会后音频转写",
        status: "needs_config",
        endpoint: "http://asr:9001",
        configFile: "config/ai-services.example.env",
      },
      {
        name: "LLM",
        role: "纪要摘要、待办提取",
        status: "needs_config",
        endpoint: "http://vllm:8000/v1",
        configFile: "config/ai-services.example.env",
      },
    ],
    searchResults: [
      {
        meetingId: "m-001",
        title: "经营预算复盘",
        speaker: "陈越",
        snippet: "预算审批和客户存储配置需要在试点启动前完成。",
        timestamp: "00:12:38",
      },
      {
        meetingId: "m-002",
        title: "产品迭代评审",
        speaker: "周敏",
        snippet: "LiveKit 录制完成后触发转写、纪要和归档任务。",
        timestamp: "00:08:11",
      },
    ],
  };
}
